fix: component检查错误

diff --git a/.github/workflows/05-merge-into-testing.yml b/.github/workflows/05-merge-into-testing.yml
--- a/.github/workflows/05-merge-into-testing.yml
+++ b/.github/workflows/05-merge-into-testing.yml
@@ -55,7 +55,16 @@ jobs:
           osc co deepin:CI:TestingIntegration:${TOPIC} && cd $_
           osc submitrequest --separate-requests deepin:Testing:"$COMPONENT" -m "${MSG}" --yes > sr.output|| true
           mergeid=$(cat sr.output |grep "created:" |awk '{print $3}')
-          echo "mergeid=$mergeid" >> $GITHUB_OUTPUT
+          if [ -n "$mergeid" ];then
+            echo "mergeid=$mergeid" >> $GITHUB_OUTPUT
+            osc request accept -m "${MSG}" $mergeid ||true
+          else
+            skip=$(cat sr.output|grep "Skipping" ||true )
+            if [ -z "$skip" ];then
+              echo "obs merge request failed!"
+              exit 1
+            fi
+          fi
 
       - name: Return merge status to pr
         uses: actions/github-script@v6
